replicaCount: 2

image:
  repository: nginx
  tag: 1.21.1
  pullPolicy: IfNotPresent

service:
  name: my-helm-chart-service
  port: 80
  type: LoadBalancer

# ingress:
#   enabled: true
#   annotations: {}
#   path: /

persistence:
  enabled: true
  storageClassName: nfs-csi
  accessMode: ReadWriteOnce
  size: 2Gi
