replicaCount: 1

image:
  repository: nginx
  tag: 1.21.1
  pullPolicy: IfNotPresent

service:
  port: 80
  type: ClusterIP
  # loadBalancerIP: 192.168.0.2

# ingress:
#   enabled: true
#   annotations: {}
#   path: /

persistence:
  enabled: true
  storageClassName: ""
  accessMode: ReadWriteOnce
  size: 2Gi
