apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
spec:
  capacity:
    # storage: 5Gi
    storage: {{ .Values.persistence.size }}
  accessModes:
    # - ReadWriteOnce
    - {{ .Values.persistence.accessMode}}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/{{ .Release.Name }}-pv
